version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
    environment:
      ZK_SERVER: "tasks.zookeeper"
  broker:
    image: qnib/uplain-kafka@sha256:cbd86f54dbf41b4dbdf25f6fe8af03452c7f0237e2ebf8e29ff9591cfe39e03d
    ports:
      - "9092:9092"
    environment:
      SWARM_TASK_ID: '{{.Task.Slot}}'
      ZK_SERVERS: "tasks.zookeeper"
      ADVERTISED_LISTENERS: "tasks.broker"
